apiVersion: v1
kind: Service

metadata:
  name: react-app-service

spec:
  type: NodePort
  # Aca sucede la magia! el servicio enviara trafico a cualquier pod que tenga la etiqueta app: react-frontend
  selector:
    app: react-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000